#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py migrate

if [ "${USE_RUNSERVER:-false}" = "true" ]; then
  exec python manage.py runserver_plus 0.0.0.0:8000
else
  exec daphne -b 0.0.0.0 -p 8000 config.asgi:application
fi
